apiVersion: apps/v1
kind: Deployment
metadata:
  name: task15-api
  namespace: task15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task15-api
  template:
    metadata:
      labels:
        app: task15-api
    spec:
      containers:
        - name: api
          image: task15-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
